### ISSUE TITLE
Wigner transform of electromagnetic pulse

### ISSUE THREAD

**Issue by laxmisubramanyam** [ljbkusters/python-wigner-distribution#3]
Dear code developer,

I am wondering if I can apply this for an electromagnetic pulse to see its frequency components.

**Comment by ljbkusters** [comment]
In principle I would say yes. Simply take the 1D waveform (like the one in your example data in the upper left corner) and apply the Wigner transform. You will get a time-frequency distribution of the signal (where in your data it would seem that time would be analogous to wavelength and frequency would be analogous to wavenumber).

The lower example to me already seems like a spectral density plot so that would be the result of entering a 1D waveform into the Wigner distribution (or some other time-frequency distribution like the STFT or spectrogram).

I'm not entirely sure how one would apply this Wigner transform to a 2D waveform except perhaps doing one transform along one axis (say the y-axis) for each bin in the other axis (say the x-axis). The resulting spectrum would then be a 3-dimensional graph though, so I'm not sure how you would go about visualizing that.

Have you tried using it?

**Comment by laxmisubramanyam** [comment]
Hi @ljbkusters, thank you for your kind reply. 

Yet I am trying to figure out how to install  ```python-winner-distribution``` on my PC. 

It was written that ```To install this module, clone this repository, open a terminal and go to the root directory of this repository. Then run pip install . or pip install -e . for development.``` But no clear directions are given how to do the cloning. 

Please, could you guide me through the installation procedure ?

Thank you.

**Comment by ljbkusters** [comment]
You can clone this directory using the command `git clone https://github.com/ljbkusters/python-wigner-distribution`. However, since you're asking this question I take it you're not familiar with git and may not have it installed on your system.

The `git clone` command is simply a way to download the source code contained in this repository. As an alternative, you could simply download a copy as a zip file by going to this repo's homepage and clicking the green 'code' dropdown (top right corner) and then select the zip download button.

Do you know how to use pip to manage python packages?

**Comment by laxmisubramanyam** [comment]
Hi @ljbkusters, thank you for your kind reply. You are simply a great personality. 

Yes, you are correct, I am not familiar with git and I haven't installed it on my system. However, I do manage to install python softwares using pip (for eg., numpy , Matplotlib, scipy etc)

**I followed your suggestions and now I am able to install the package (python-winner-distribution) and also made successful test of the file inside the directory (test).** 

Now, I am going to see if I can use it for making a Wigner transform of the laser electric field I have (1D). If I am not able to do it, I will come back to you for help. 

Thanks a lot.

**Comment by laxmisubramanyam** [comment]
Hi @ljbkusters, 

I tried to make the Wigner transform. I think I am doing it correctly, but I have no idea what frequency it is giving to me. ```The central wavelength of my laser pulse is 0.8 μm (omega=2.35e15). ```

Please, find attached the python script (```Python_script.txt```) I am using to make the Wigner transform, the 1D data of the electric field (```Data_Efield_1D.txt```) and the generated figure.

Please, could you help me to check if I am doing the winger transform correctly and how to identify the correct frequency (wavenumber in my case). Please, change the extension of ```Python_script``` file to ```.py```.

Thanks a lot.

[Python_script.txt](https://github.com/user-attachments/files/18113361/Python_script.txt)
[Data_Efield_1D.txt](https://github.com/user-attachments/files/18113362/Data_Efield_1D.txt)
<img width="1090" alt="Figure" src="https://github.com/user-attachments/assets/563768da-328f-448a-b696-593eb7bea198" />

**Comment by ljbkusters** [comment]
The wigner distribution method, like a fourier transform, returns the frequency spectrum in bins. The maximum frequency `fmax` belonging to the maximum frequency bin is dependent on the sample frequency `fs` and should be given by `fmax=fs/2`. The second return value of the wiger distribution method already returns this frequency `fmax`. Please refer to the docstring.

So then the frequency belonging to each bin in the frequency dimension would be the bin's index `k` devided by the number of bins in the frequency dimension `N_f=wigner_dist.shape[1]` times the max frequency `fmax`, or in other terms `f_k= fmax * k / N_f` (where `wigner_dist` would be the 2d array returned by the wigner distribution method)

**Comment by laxmisubramanyam** [comment]
Hi @ljbkusters,

Thanks for your suggestions. I think following your advice I am able to see the correct angular frequency of the laser pulse. I made the following changes in the ```my python script```

```
dx = Xaxis[1] - Xaxis[0] # x-axis resolution / sampling
Ts = dx/c                # sampling time
Fs = 1/Ts                # sampling frequency
Fs = 2.0 * np.pi * Fs    # smapling angular frequency

plot_wigner_distribution(wigner_dist, title='test', max_freq=Fs/2, min_time=Xmin/c, max_time=Xmax/c)
```

converting the ```spatial scale of the X-axis to time (min_time=Xmin/c, max_time=Xmax/c)``` also gives me close to correct pulse duration as well. 

**Do you think, I did it correctly ?**
